//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace payment_remastered_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Бланк
    {
        public int Код_бланка { get; set; }
        public Nullable<int> Бухгалтер { get; set; }
        public Nullable<int> Студент { get; set; }
        public Nullable<int> Оплата { get; set; }
    
        public virtual Бухгалтер Бухгалтер1 { get; set; }
        public virtual Оплата Оплата1 { get; set; }
        public virtual Студент Студент1 { get; set; }
    }
}
