//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace payment_remastered_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Задолжность
    {
        public int Код_задолжности { get; set; }
        public Nullable<decimal> Сумма_задолжености { get; set; }
        public Nullable<int> Студент { get; set; }
    
        public virtual Студент Студент1 { get; set; }
    }
}
