//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace payment_remastered_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оплата
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Оплата()
        {
            this.Бланк = new HashSet<Бланк>();
        }
    
        public int Код_оплаты { get; set; }
        public Nullable<decimal> Сумма_оплаты { get; set; }
        public Nullable<System.DateTime> Дата_оплаты { get; set; }
        public Nullable<int> Студент { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Бланк> Бланк { get; set; }
        public virtual Студент Студент1 { get; set; }
    }
}
